# Generated by Django 3.2.16 on 2023-01-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_all_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.recipe', verbose_name='Рецепт'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='numberingredient',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='number_ingredient_unique'),
        ),
    ]
