# Generated by Django 3.2.16 on 2023-01-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_in_recepie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Выберите ингредиенты для рецепта', related_name='recipes', through='api.NumberIngredient', to='api.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
